# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect
# YOLOv8s-MobileNetv3 summary: 350 layers, 6357718 parameters, 6357702 gradients, 16.3 GFLOPs
# Parameters
nc: 80  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8-SPPCSPC.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]  # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024]  # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768]   # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512]   # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512]   # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
    # MobileNetV3-small 11层
    # [from, number, module, args]
    # MobileNet_Block: [out_ch, hidden_ch, kernel_size, stride, use_se, use_hs]
    # hidden_ch表示在Inverted residuals中的扩张通道数
    # use_se 表示是否使用 SELayer, use_hs 表示使用 h_swish 还是 ReLU
  # [from, repeats, module, args]
  - [-1, 1, conv_bn_hswish, [16, 2]]                 # 0-p1/2
  - [-1, 1, MobileNet_Block, [16,  16, 3, 2, 1, 0]]  # 1-p2/4
  - [-1, 1, MobileNet_Block, [24,  72, 3, 2, 0, 0]]  # 2-p3/8
  - [-1, 1, MobileNet_Block, [24,  88, 3, 1, 0, 0]]  # 3-p3/8
  - [-1, 1, MobileNet_Block, [40,  96, 5, 2, 1, 1]]  # 4-p4/16
  - [-1, 1, MobileNet_Block, [40, 240, 5, 1, 1, 1]]  # 5-p4/16
  - [-1, 1, MobileNet_Block, [40, 240, 5, 1, 1, 1]]  # 6-p4/16
  - [-1, 1, MobileNet_Block, [48, 120, 5, 1, 1, 1]]  # 7-p4/16
  - [-1, 1, MobileNet_Block, [48, 144, 5, 1, 1, 1]]  # 8-p4/16
  - [-1, 1, MobileNet_Block, [96, 288, 5, 2, 1, 1]]  # 9-p5/32
  - [-1, 1, MobileNet_Block, [96, 576, 5, 1, 1, 1]]  # 10-p5/32
  - [-1, 1, MobileNet_Block, [96, 576, 5, 1, 1, 1]]  # 11-p5/32
#  - [-1, 1, SPPF, [1024, 5]]  # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 8], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 14

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 3], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 17 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 14], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 20 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 11], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 23 (P5/32-large)

  - [[17, 20, 23], 1, Detect, [nc]]  # Detect(P3, P4, P5)
